version: '2'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vollmed_api
      MYSQL_PASSWORD: password
    volumes:
      - /dados/db:/var/lib/mysql
    ports:
      - '3306:3306'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATASOURCE_URL=jdbc:mysql://db:3306/vollmed_api
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=password
    ports:
      - '8080:8080'
    depends_on:
      - db
